export const SESSION_COOKIE = Symbol('SESSION_COOKIE');
export const AUTH_LOGIN_IP_LIMITER = Symbol('AUTH_LOGIN_IP_LIMITER');
export const AUTH_LOGIN_EMAIL_IP_LIMITER = Symbol('AUTH_LOGIN_EMAIL_IP_LIMITER');
export const AUTH_REFRESH_IP_LIMITER = Symbol('AUTH_REFRESH_IP_LIMITER');
export const AUTH_ENDPOINT_IP_LIMITER = Symbol('AUTH_ENDPOINT_IP_LIMITER');
