export const ROLE_REPOSITORY = Symbol('ROLE_REPOSITORY');
export const PERMISSION_REPOSITORY = Symbol('PERMISSION_REPOSITORY');
export const ROLE_ASSIGNMENT_REPOSITORY = Symbol('ROLE_ASSIGNMENT_REPOSITORY');
export const AUTHORIZATION_EVENT_PUBLISHER = Symbol('AUTHORIZATION_EVENT_PUBLISHER');
export const AUTHORIZATION_CONTEXT_RESOLVER = Symbol('AUTHORIZATION_CONTEXT_RESOLVER');
export const RBAC_POLICY = Symbol('RBAC_POLICY');
export const ABAC_POLICY = Symbol('ABAC_POLICY');
