export const OUTBOX_REPOSITORY = Symbol('OUTBOX_REPOSITORY');
export const OUTBOX_DEAD_LETTER_REPOSITORY = Symbol('OUTBOX_DEAD_LETTER_REPOSITORY');
export const OUTBOX_EVENT_PUBLISHER = Symbol('OUTBOX_EVENT_PUBLISHER');
export const OUTBOX_CLOCK = Symbol('OUTBOX_CLOCK');
export const OUTBOX_EVENT_CATALOG_POLICY = Symbol('OUTBOX_EVENT_CATALOG_POLICY');
