export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PASSWORD_IDENTITY_REPOSITORY = Symbol('PASSWORD_IDENTITY_REPOSITORY');
export const SESSION_REPOSITORY = Symbol('SESSION_REPOSITORY');
export const CHALLENGE_DELIVERY = Symbol('CHALLENGE_DELIVERY');
export const IDENTITY_EVENT_PUBLISHER = Symbol('IDENTITY_EVENT_PUBLISHER');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const TRANSACTION_RUNNER = Symbol('TRANSACTION_RUNNER');
