export const INSTITUTION_REPOSITORY = Symbol('INSTITUTION_REPOSITORY');
export const INSTITUTION_SETTINGS_REPOSITORY = Symbol('INSTITUTION_SETTINGS_REPOSITORY');
export const MEMBERSHIP_REPOSITORY = Symbol('MEMBERSHIP_REPOSITORY');
export const INVITATION_REPOSITORY = Symbol('INVITATION_REPOSITORY');
export const TENANT_TRANSACTION_RUNNER = Symbol('TENANT_TRANSACTION_RUNNER');
export const TENANT_EVENT_PUBLISHER = Symbol('TENANT_EVENT_PUBLISHER');
export const TENANT_CONTEXT_RESOLVER = Symbol('TENANT_CONTEXT_RESOLVER');
export const INVITATION_TOKEN_HASHER = Symbol('INVITATION_TOKEN_HASHER');
