export const PLAN_REPOSITORY = Symbol('PLAN_REPOSITORY');
export const FEATURE_DEFINITION_REPOSITORY = Symbol('FEATURE_DEFINITION_REPOSITORY');
export const TENANT_ENTITLEMENT_REPOSITORY = Symbol('TENANT_ENTITLEMENT_REPOSITORY');
export const USAGE_QUOTA_REPOSITORY = Symbol('USAGE_QUOTA_REPOSITORY');
export const USAGE_METER_REPOSITORY = Symbol('USAGE_METER_REPOSITORY');
export const ENTITLEMENTS_TRANSACTION_RUNNER = Symbol('ENTITLEMENTS_TRANSACTION_RUNNER');
export const ENTITLEMENTS_CONTEXT_RESOLVER = Symbol('ENTITLEMENTS_CONTEXT_RESOLVER');
export const ENTITLEMENTS_EVENT_PUBLISHER = Symbol('ENTITLEMENTS_EVENT_PUBLISHER');
